package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("twitch.tvuiTests")
    void generatedTest() {
        step("Open \"https://www.twitch.tv/\"", () -> {
            step("// todo: just add selenium action");
        });

        step("click login button", () -> {
            step("// todo: just add selenium action");
        });

        step("check login formis open", () -> {
            step("// todo: just add selenium action");
        });

        step("login", () -> {
            step("// todo: just add selenium action");
        });

        step("check logged in", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.twitch.tv/'", () ->
            open("https://www.twitch.tv/"));

        step("Page title should have text 'Twitch'", () -> {
            String expectedTitle = "Twitch";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.twitch.tv/'", () ->
            open("https://www.twitch.tv/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}